### ISSUE TITLE
Plugin start failure: Failed to find a suitable library for volume s3 

### ISSUE THREAD

**Issue by clibequilibrium** [eclipse-zenoh/zenoh-backend-s3#2]
Hello. 

I am trying to deploy zenohd with Docker and S3 backend however my library isn't loading. 
it fails on container startup with 

`Plugin start failure: Failed to find a suitable library for volume s3  (was looking for <lib>zbackend_s3<.so/.dll/.dylib>) at plugins/zenoh-plugin-storage-manager/src/lib.rs:192. 1 [2022-11-21T06:22:10Z INFO  zenohd] Finished loading plugins`

It's odd because rocksdb backend getting loaded successfully when dropped in the root directory of the container.

EDIT: the issue was solved and the reason is I wasn't using x86_64-unknown-linux-musl version of the library. I think the error should be corrected to reflect this reason other than related to the library path.

**Comment by DariusIMP** [comment]
This was an old issue that iirc was due to a change in the libs name. I think we can close it.
