### ISSUE TITLE
Improve logging when Minio TLS enabled

### ISSUE THREAD

**Issue by clibequilibrium** [eclipse-zenoh/zenoh-backend-s3#3]
Hello,

I am deploying Minio in Kubernetes and I have TLS option enabled requestAutoCert = true. However when trying to connect over https , the backend fails to connect with certificate error. So I forced the config file to connect via http but it produces no errors and does not connect either. I propose to improve logging if the connection to the bucket isn't successful in the case of http connection to Minio TLS secured instance.  

What I ended up doing for now is disabling TLS in my Minio instance and now I can see the bucket got auto created. Thanks !

![image](https://user-images.githubusercontent.com/105135724/202987121-37076644-bd26-4d7d-ac3a-bf22f84067a9.png)

**Comment by DariusIMP** [comment]
Thanks for pointing this out. I've seen the aws sdk s3 library we are using underneath this code allows us to configure TLS parameters so I'll see if its feasible to implement that option in the short term, otherwise yes, as a temporary measure I'll try to improve those logs.
